services:
    discord-game-server-monitor:
        container_name: discord-game-server-monitor
        build:
          context: .
          dockerfile: Dockerfile
        image: discord-game-server-monitor:local
        restart: on-failure
        volumes:
          - type: bind
            source: ./discord-game-server-monitor-data
            target: /usr/src/app/data
        environment:
            - APP_TOKEN=CHANGEME
            - WHITELIST_GUILDS=CHANGEME
        command: python main.py

volumes:
    discord-game-server-monitor-data:
        external: true
        name: discord-game-server-monitor-data
